### PR TITLE
Keep the number of channels as-is by default when selecting Opus.

### PR DESCRIPTION
**Pull request by BassThatHertz**
I'm not sure why stereo was set as the default output channel layout when selecting Opus. Also, I improved the code for the input file extension check. This way is cleaner than having a bunch of "or"s.

### CODE REVIEW

**Comment by jlw4049** [comment]
I was having issues when leaving the codec set to Original and the source was a 5.1(side) source. 

It would error out because opus only supports 5.1 non side. 

To avoid this I removed original from the selection.

**Comment by jlw4049** [comment]
Once i get back on my PC I will take a look at rest etc

**Comment by BassThatHertz** [comment]
>It would error out because opus only supports 5.1 non side.
Just tested this and you're right. That's no bueno. In that case, I have reverted the changes made with regards to Opus, but I still recommend merging this PR as the code for checking whether the input file extension is supported is cleaner.

**Comment by jlw4049** [comment]
> >It would error out because opus only supports 5.1 non side.
> Just tested this and you're right. That's no bueno. In that case, I have reverted the changes made with regards to Opus, but I still recommend merging this PR as the code for checking whether the input file extension is supported is cleaner.

I plan to eventually type up some logic for using mediainfo to check the track information/channels when selected.

This will allow original to be put back and i could make the program automatically select -ac 6 or 2 or what ever it needed. Until then the best solution I could come up with was requiring user input for this codec unfortunately.

**Comment by jlw4049** [comment]
I have merged it! Thanks!

**Pull request merged**
